@host = http://localhost:5000/chat

### ask question
POST {{host}}
Content-Type: application/json

{
  "message": "list out Raj kumar skill set"
}


### ask question from embedded
POST {{host}}
Content-Type: application/json

{
  "message": "list out Raj kumar skill set as per last embedding given"
}
