@host = http://localhost:5000/chat

### ask question
POST {{host}}
Content-Type: application/json

{
  "message": "What is Redink Classroom?"
}


### ask question from embedded
POST {{host}}/from-embedding
Content-Type: application/json

{
  "message": "What is Redink Classroom?"
}
